valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w41> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w41> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w70> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w70> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w33> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w33> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w11> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w11> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w13> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w13> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w36> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w36> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w52> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w52> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w07> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w07> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w06> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w06> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w10> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w10> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w78> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w78> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w46> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w46> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w18> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w18> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w77> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w77> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w68> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w68> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w50> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w50> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w76> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w76> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w65> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w65> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w38> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w38> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w67> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w67> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w75> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w75> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w37> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w37> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w12> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w12> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w74> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w74> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w66> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w66> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w69> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w69> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w23> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w23> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w42> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w42> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w20> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w20> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w16> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w16> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w61> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w61> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w35> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w35> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w14> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w14> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w40> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w40> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w22> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w22> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w31> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w31> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w17> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w17> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w34> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w34> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w04> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w04> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w57> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w57> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w51> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w51> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w01> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w01> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w30> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w30> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w53> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w53> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w32> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w32> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w39> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w39> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w71> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w71> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w54> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w54> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w27> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w27> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w19> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w19> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w24> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w24> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w28> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w28> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w62> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w62> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w55> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w55> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w05> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w05> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w64> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w64> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w29> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w29> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w09> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w09> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w73> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w73> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w00> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w00> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w56> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w56> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w21> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w21> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w26> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w26> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w08> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w08> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w72> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w72> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w03> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w03> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w02> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w02> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w15> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w15> saida.txt
valgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w25> saida.txtvalgrind --leak-check=full --show-leak-kinds=all -s ./etapa3 < Pasta/w25> saida.txt
